### ISSUE TITLE
[SciComp] Finish Tasks in Old GitHub Project

### ISSUE THREAD

**Issue by njlyon0** [lter/scicomp#2]
## Summary

Need to finish the lingering tasks I have in our old GitHub Project. This follows from #1 . See [Enterprise #300](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/300) for the overview

## Starting Tasks

- [x] Finish/migrate [Enterprise #281](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/281) - Update LTER Site Boundaries
    - Nearly done, leaving in current location
- [x] Finish/migrate [Enterprise #282](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/282) - Continue to Develop Python literacy
    - Still at start of task + limited content in non-top-level comment so migrating it
    - See #4 
- [x] Finish/migrate [Enterprise #283](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/283) - Work through Advanced R book 
    - Task likely a ways from done but progress reports aren't vital so migrating it
    - See #6 
- [x] Finish/migrate [Enterprise #293](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/293) - Onboard Resilience WG 
    - Nearly done plus small scope of task so leaving where it is)
- [x] Finish/migrate [Enterprise #294](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/294) - Onboard CAGED WG
    - Task set but can't start until after their initial onboarding so migrating it
    - See #5 
- [x] Finish/migrate [Enterprise #298](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/298) - Write Data Bits Article 
    - Task incomplete but can safely migrate / recap progress to this point so migrating it
    - See #7 

## Useful links

- GitHub Enterprise [Project](https://github.nceas.ucsb.edu/orgs/LTER/projects/8/views/1) (for NJL)

**Comment by njlyon0** [comment]
## Migrations Done

Finished migrating the issues where I think that makes sense. The two I left alone are both nearly done and have significant information in the thread of comments so I'm leaving them where they're at (at least for now)

**Comment by njlyon0** [comment]
## Site Boundaries Updated

LTER site boundary data product updated on EDI (see [edi.1686.2](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1686.2))! That was my last task in old system so I'm closing this issue
